config/routes.rb
Rails.application.routes.draw do
  resources :contacts
  
  if Rails.env.development?
  mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

  resources :sessions
  resources :users

  resources :blogs do
    collection do
      post :confirm
    end
  end

  root :to => "blogs#top"

  resources :favorites, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/blog.rb
class Blog < ApplicationRecord
  validates :title, presence: true
  validates :content, length: {in: 1..140}

  belongs_to :user, optional: true, foreign_key: 'user_id'
  has_many :favorites, dependent: :destroy
  has_many :favorite_user, through: :favorites, source: :user

  mount_uploader :image, ImageUploader
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :blog
end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true, length: { maximum: 30}
  validates :email, presence: true, length: { maximum: 255},
               format: { with: /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i }

  before_save { email.downcase! }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6}

  has_many :blogs, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorite_blogs, through: :favorites, source: :blog

  mount_uploader :icon, ImageUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  before_action :set_current_user

  def set_current_user
    @current_user = User.find_by(id: session[:user_id])
  end

  def authenticate_user
    if @current_user == nil
      flash[:notice] = "ログインが必要です"
      redirect_to new_session_path
    end
  end
end

app/controllers/blogs_controller.rb
class BlogsController < ApplicationController
  before_action :set_blog, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user, only: [:new, :show, :edit]

  def top
  end

  def index
    @blogs = Blog.all
  end

  def new
    if params[:back]
      @blog = Blog.new(blog_params)
    else
      @blog = Blog.new
    end
  end

  def create
    @blog = Blog.new(blog_params)
    @blog.user_id = current_user.id
    @blog.image.retrieve_from_cache! params[:cache][:image]
    @blog.save!
    if @blog.save
      ContactMailer.contact_mail(@blog).deliver
      redirect_to blogs_path, notice: "ブログを作成しました！"
    else
      render 'new'
    end
  end

  def show
    @blog
    @favorite = current_user.favorites.find_by(blog_id: @blog.id)
  end

  def edit
   @blog = Blog.find(params[:id])
    if @blog.user_id != @current_user.id
      flash[:notice] = "自分の投稿ではありません"
      redirect_to blogs_path
    end
  end

  def update
    if @blog.update(blog_params)
      redirect_to blogs_path, notice: "ブログを編集しました！"
    else
      render 'edit'
    end
  end

  def destroy
    if @blog.user_id == @current_user.id
      @blog.destroy
      redirect_to blogs_path, notice:"ブログを削除しました！"
    else
      redirect_to blogs_path, notice:"自分の投稿ではありません"
    end
  end

  def confirm
    @blog = Blog.new(blog_params)
    render 'new' if @blog.invalid?
  end

  private
  def blog_params
    params.require(:blog).permit(:title, :content, :image)
  end

  def set_blog
    @blog = Blog.find(params[:id])
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :set_contact, only: [:show, :edit, :update, :destroy]

  # GET /contacts
  # GET /contacts.json
  def index
    @contacts = Contact.all
  end

  # GET /contacts/1
  # GET /contacts/1.json
  def show
  end

  # GET /contacts/new
  def new
    @contact = Contact.new
  end

  # GET /contacts/1/edit
  def edit
  end

  # POST /contacts
  # POST /contacts.json
  def create
    @contact = Contact.new(contact_params)

    respond_to do |format|
      if @contact.save
        ContactMailer.contact_mail(@contact).deliver
        format.html { redirect_to @contact, notice: 'Contact was successfully created.' }
        format.json { render :show, status: :created, location: @contact }
      else
        format.html { render :new }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /contacts/1
  # PATCH/PUT /contacts/1.json
  def update
    respond_to do |format|
      if @contact.update(contact_params)
        format.html { redirect_to @contact, notice: 'Contact was successfully updated.' }
        format.json { render :show, status: :ok, location: @contact }
      else
        format.html { render :edit }
        format.json { render json: @contact.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /contacts/1
  # DELETE /contacts/1.json
  def destroy
    @contact.destroy
    respond_to do |format|
      format.html { redirect_to contacts_url, notice: 'Contact was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_contact
      @contact = Contact.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def contact_params
      params.require(:contact).permit(:name, :email, :content)
    end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    favorite = current_user.favorites.create(blog_id: params[:blog_id])
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り登録しました"
  end

  def destroy
    favorite = current_user.favorites.find_by(blog_id: params[:blog_id])
    favorite.destroy
    redirect_to blogs_url, notice: "#{favorite.blog.user.name}さんのブログをお気に入り解除しました"
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      redirect_to user_path(user.id)
    else
      flash[:danger] = 'ログインに失敗しました'
      redirect_to new_session_path
    end
  end

  def destroy
    session.delete(:user_id)
    flash[:notice] = 'ログアウトしました'
    redirect_to new_session_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.create(user_params)
    if @user.save
      redirect_to user_path(@user.id)
    else
      render 'new'
    end
  end

  def show
    @user = User.find(params[:id])
    @favorites_blogs = @user.favorite_blogs
  end

  private
  def user_params
    params.require(:user).permit(:name,:email,:password,:password_confirmation,:icon)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/blogs_helper.rb
module BlogsHelper
  def choose_new_or_edit
    if action_name == 'new' || action_name == 'confirm'
      confirm_blogs_path
    elsif action_name == 'edit'
      blog_path
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end

  def logged_in?
    !current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %><br>
    <%= form.text_field :title , style: "border-radius:5px"%>
  </div>
  <div class="blog_title">
    <%= form.label :content %><br>
    <%= form.text_field :content , :size=>"60*10" , style: "border-radius:5px"%>
  </div>
  <div class="blog_title">
  <%= form.label :画像 %>
  <%= form.file_field :image, id: :feed_image %>
  <%= form.hidden_field :image_cache %>
  </div>
  <div class="create-btn">
  <%= form.submit "登録する" , style: "border-radius:5px"%>
</div>
<% end %>

app/views/blogs/confirm.html.erb
<div class="check-page">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <p>画像:<%= image_tag @blog.image %></p>
  <%= hidden_field_tag :"cache[image]",@blog.image.cache_name %>
  <%= form.submit  "登録する" , style: "border-radius:5px"%>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.hidden_field :image %>
  <%= form.submit "もどる", name: 'back' , style: "border-radius:5px"%>
<% end %>
</div>

app/views/blogs/index.html.erb
<div class="index-page">
  <h2>ブログ一覧</h2>
<p><%= notice %></p>


<% @blogs.each do |blog| %>
    <h3>タイトル: <%= blog.title %></h3><br>
    <h3>内容: <%= blog.content %></h3><br>
    <h3>画像: <%= image_tag blog.image %></h3><br>
    <button type="button" class="btn btn-primary"><%= link_to '詳細', blog_path(blog.id)%></button>
    <% if blog.user == current_user %>
    <button type="button" class="btn btn-success"><%= link_to "編集", edit_blog_path(blog.id) %></button>
    <button type="button" class="btn btn-danger"><%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button><br>
    <% end %>
<% end %>
</div>

app/views/blogs/show.html.erb
<div class="show-page">
<h2>ブログ詳細画面</h2>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<p>画像: <%= image_tag @blog.image %></p>
<button type="button" class="btn btn-primary">
  <a href="/blogs">戻る</a>
</button>
<% unless @blog.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-warning' %>
  <% end %>
<% end %>
</div>

app/views/contacts/_form.html.erb
<%= form_with(model: contact, local: true) do |form| %>
  <% if contact.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(contact.errors.count, "error") %> prohibited this contact from being saved:</h2>

      <ul>
      <% contact.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :contact_name %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email, id: :contact_email %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :contact_content %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h1>Editing Contact</h1>

<%= render 'form', contact: @contact %>

<%= link_to 'Show', @contact %> |
<%= link_to 'Back', contacts_path %>

app/views/contacts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Contacts</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Email</th>
      <th>Content</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.email %></td>
        <td><%= contact.content %></td>
        <td><%= link_to 'Show', contact %></td>
        <td><%= link_to 'Edit', edit_contact_path(contact) %></td>
        <td><%= link_to 'Destroy', contact, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Contact', new_contact_path %>

app/views/contacts/new.html.erb
<div class=new-contact-page>
<h2>New Contact</h2>

<%= render 'form', contact: @contact %>

<%= link_to 'Back', contacts_path %>
</div>

app/views/contacts/show.html.erb
<div class=show-contact-page>
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @contact.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @contact.email %>
</p>

<p>
  <strong>Content:</strong>
  <%= @contact.content %>
</p>

<%= link_to 'Edit', edit_contact_path(@contact) %> |
<%= link_to 'Back', contacts_path %>
</div>

app/views/it.html.erb/_form.html.erb
<%= form_with(model: @blog, local: true, url: choose_new_or_edit) do |form| %>
  <% if @blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= @blog.errors.count %>件のエラーがあります。</h2>
      <ul>

      <% @blog.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="blog_title">
    <%= form.label :title %><br>
    <%= form.text_field :title , style: "border-radius:5px"%>
  </div>
  <div class="blog_title">
    <%= form.label :content %><br>
    <%= form.text_field :content , :size=>"60*10" , style: "border-radius:5px"%>
  </div>
  <div class="create-btn">
  <%= form.submit "登録する" , style: "border-radius:5px"%>
</div>
<% end %>

app/views/it.html.erb/confirm.html.erb
<div class="check-page">
<h3>以下の内容で、送信する。</h3>

<%= form_with(model: @blog, url: blogs_path, local: true) do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>

  <p>タイトル:<%= @blog.title %></p>
  <p>本文:<%= @blog.content %></p>
  <%= form.submit  "登録する" , style: "border-radius:5px"%>
<% end %>

<%= form_with(model: @blog, url: new_blog_path, local: true, method: 'get') do |form| %>
  <%= form.hidden_field :title %>
  <%= form.hidden_field :content %>
  <%= form.submit "もどる", name: 'back' , style: "border-radius:5px"%>
<% end %>
</div>

app/views/it.html.erb/edit.html.erb
<div class="edit-page">
<h2>ブログを編集する</h2>

<%= render 'form' %>
</div>

app/views/it.html.erb/index.html.erb
<div class="index-page">
  <h2>ブログ一覧</h2>
<p><%= notice %></p>


<% @blogs.each do |blog| %>
    <h3>タイトル: <%= blog.title %></h3><br>
    <h3>内容: <%= blog.content %></h3><br>
    <button type="button" class="btn btn-primary"><%= link_to '詳細', blog_path(blog.id)%></button>
    <% if blog.user_id == current_user.id %>
    <button type="button" class="btn btn-success"><%= link_to "編集", edit_blog_path(blog.id) %></button>
    <button type="button" class="btn btn-danger"><%= link_to '削除', blog_path(blog.id), method: :delete, data: { confirm: '本当に削除していいですか？' } %></button><br>
    <% end %>
<% end %>
</div>

app/views/it.html.erb/new.html.erb
<div class="new-page">
<h2>ブログを作成する</h2>

<%= render 'form' %>
</div>

app/views/it.html.erb/show.html.erb
<div class="show-page">
<h2>ブログ詳細画面</h2>
<p>タイトル: <%= @blog.title %></p>
<p>内容: <%= @blog.content %></p>
<button type="button" class="btn btn-primary">
  <a href="/blogs">戻る</a>
</button>
<% unless @blog.user == current_user %>
  <% if @favorite.present? %>
    <%= link_to 'お気に入り解除する', favorite_path(blog_id: @blog.id), method: :delete, class: 'btn btn-danger' %>
  <% else %>
    <%= link_to 'お気に入りする', favorites_path(blog_id: @blog.id), method: :post, class: 'btn btn-warning' %>
  <% end %>
<% end %>
</div>

app/views/it.html.erb/top.html.erb
<div class="top-content">
  <div class="box">
    <p>日常を楽しもう。</p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Bolgs</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
      <header>
        <nav class="navbar navbar-default">
          <div class="container-fluid">
            <div class="navbar-header">
              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#gnavi">
                <span class="sr-only">Bootstrap</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>
              <a class="navbar-brand" href="/">Blog</a>
            </div>
            <div id="gnavi" class="collapse navbar-collapse">
              <ul class="nav navbar-nav">
                <li>
                  <a href="/blogs">投稿一覧</a>
                </li>
                <li>
                  <a href="/blogs/new">新規投稿</a>
                </li>
                <% if logged_in? %>
                  <li><%= link_to "Profile", user_path(current_user.id) %></li>
                  <li><%= link_to "Logout", session_path(current_user.id), method: :delete %></li>
                <% else %>
                  <li><%= link_to "Sign up", new_user_path %></li>
                  <li><%= link_to "Login", new_session_path %></li>
                <% end %>
              </ul>
            </div>
          </div>
        </nav>
      </header>
      <div class="margin-top"></div>
      <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
      <% end %>
        <%= yield %>
      <footer class="footer">
        <div class="container">
          <p class="text-muted">201710 Blog application.</p>
        </div>
      </footer>

  </body>
</html>

app/views/users/new.html.erb
<div class="signup-page">
<h2>Sign up</h2>

<% if @user.errors.any? %>
  <div id="error_explanation">
    <h2><%= pluralize(@user.errors.count, "error") %> prohibited this @user from being saved:</h2>
    <ul>
    <% @user.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
    </ul>
  </div>
<% end %>

<%= form_with(model: @user, local: true) do |f| %>
  <%= f.label :name %><br>
  <%= f.text_field :name %><br><br>

  <%= f.label :email %><br>
  <%= f.email_field :email %><br><br>

  <%= f.label :icon %><br>
  <div class=icon><%= f.file_field :icon,id: :user_icon %></div><br><br>
  <%= f.hidden_field :icon_cache %>

  <%= f.label :password %><br>
  <%= f.password_field :password %><br><br>

  <%= f.label :password_confirmation %><br>
  <%= f.password_field :password_confirmation %><br><br>

  <%= f.submit "Create my account" %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="user-page">
<h2><%= @user.name %>のページ</h2>
<p>icon: <%= image_tag @user.icon.thumb.url %></p>
<p>メールアドレス: <%= @user.email %></p>

<p>【<%= @user.name %>がお気に入りした記事】</p>
<% @favorites_blogs.each do |blog| %>
    <p>タイトル: <%= blog.title %></p><br>
    <p>内容: <%= blog.content %></p><br>
    <p>内容: <%= image_tag blog.image %></p><br>
  <% end %>
</div>
</div>